### ISSUE TITLE
incomplete migrations  ?

### ISSUE THREAD

**Issue by arhimede** [dotkernel/dot-admin#160]
after applying migrations and seeds today, we are missing a table 

PHP Fatal error:  Uncaught mysqli_sql_exception: Table 'dk_admin4.contact_message' doesn't exist in /var/www/vhosts/[admin4.dotkernel.net/httpdocs/bin/reset-db.php:35](http://admin4.dotkernel.net/httpdocs/bin/reset-db.php:35)
Stack trace:
#0 /var/www/vhosts/[admin4.dotkernel.net/httpdocs/bin/reset-db.php(35)](http://admin4.dotkernel.net/httpdocs/bin/reset-db.php(35)): mysqli->query()
#1 {main}
  thrown in /var/www/vhosts/[admin4.dotkernel.net/httpdocs/bin/reset-db.php](http://admin4.dotkernel.net/httpdocs/bin/reset-db.php) on line 35

**Comment by alexmerlin** [comment]
The table `contact_message` is not part of DK Admin, that's why the migrations did not recreate it after emptying the database.
If there is an instance of the DK Frontend that uses that same database, then the DK Frontend migrations need to be runned.
Else, the command that empties `contact_message` needs to be removed from the **reset-db.php** script.
