### ISSUE TITLE
[Insight] Your project should not contain duplicated code - in src/…/InputFilter/AdminInputFilter.php, line 20

### ISSUE THREAD

**Issue by arhimede** [dotkernel/dot-admin#248]
**[in src/Admin/src/InputFilter/AdminInputFilter.php, line 20](https://github.com/dotkernel/admin/blob/fb560ba14eac5181f5fa2e21d76ad64685d785fa/src/Admin/src/InputFilter/AdminInputFilter.php#L20)**

> The next 24 lines appear both in `src/Admin/src/InputFilter/AdminInputFilter.php:20` and `src/Admin/src/InputFilter/EditAdminInputFilter.php:20`.

```php
use Laminas\Validator\StringLength;

/**
 * @extends InputFilter<object>
 */
class AdminInputFilter extends InputFilter
{
    public function init(): void
    {
        $identity = new Input('identity');
        $identity->setRequired(true);
```

---------------------

_Posted from [SymfonyInsight](https://insight.symfony.com/projects/6a7ecfc1-a0ed-4901-96ac-d0ff61f7b55f/analyses/138)_

**Comment by pinclau** [comment]
This should be ignored as the other warning like this was. The dublicate code warning is between create and edit inputs for the admin, whatever changes we make, still will se dublicate code, as the password inputs for create needs to be required and for edit don't. I tried to make a base input filter and create and update to extend that, but still will see dublicate code because of the passwords inputs.
